-------------------------------------- insert into
INSERT INTO TB_PROVINCE (CODE, TITLE)
VALUES (11, 'تهران');

INSERT INTO TB_City (CODE, TITLE, PROVINCE_CODE)
VALUES (1101, 'تهران', 11);

INSERT INTO TB_ZONE (CODE, TITLE, CITY_CODE)
VALUES (1, 'منطقه یک ', 1101);
INSERT INTO TB_ZONE (CODE, TITLE, CITY_CODE)
VALUES (2, 'منطقه دو ', 1101);

INSERT INTO TB_ESTATE (ID, PROVINCE_CODE, CITY_CODE, ZONE_CODE,
                       DATE_YEAR, PRICE_PER_SQUARE_METER)
VALUES (1, 11, 1101, 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 150000000);

INSERT INTO TB_ESTATE (ID, PROVINCE_CODE, CITY_CODE, ZONE_CODE,
                       DATE_YEAR, PRICE_PER_SQUARE_METER)
VALUES (2, 11, 1101, 1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 120000000);

INSERT INTO TB_ESTATE (ID, PROVINCE_CODE, CITY_CODE, ZONE_CODE,
                       DATE_YEAR, PRICE_PER_SQUARE_METER)
VALUES (3, 11, 1101, 2, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 100000000);